name: 'Build Nginx'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push the docker image    
        env:
          GOOGLE_PROJECTS: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev  
          docker build -t us-central1-docker.pkg.dev/myapigee-123/demo-artifact-registry/nginx:latest .
          docker push us-central1-docker.pkg.dev/myapigee-123/demo-artifact-registry/nginx:latest

      